### ISSUE TITLE
One more magic line

### ISSUE THREAD

**Issue by dolikemedo** [goldarte/alc294_soundfix#1]
Hi!

This didn't work for me, but i found a new magic line that did:

```
sudo hda-verb /dev/snd/hwC0D0 0x20 0x400 0x7774
```

Asus vivobook pro 15 k6500ze, ubuntu 22.04.3, kernel 5.19.17

Thanks for your solution anyway!

**Comment by c-orazio** [comment]
HI , I am using an expertbook with ubuntu 22.04 with this sound card, but it did not work on  ASUS ExpertBook B9 B9400CBA-KC0590X - 14" - Intel Core i7 - 1255Uot work...
I will try to upgrade the system to 23.04

**Comment by goldarte** [comment]
Added link to @dolikemedo repo with fixes in README
